### PR TITLE
fix: prevent worker from running oom

### LINKED ISSUE #175: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
I'm trying to migrate an existing project that uses rules_nodejs (5.6.0) to rules_js (1.4.0) and rules_ts (1.0.0-rc3) and after fixing various issues and trying to build the whole repo I can't seem to ever complete a full build.

I've seen a few different log outputs from when it fails, but I'm guessing they're all symptoms of the same problem, all heap memory being allocated. I'm trying to understand if this is from bazels JVM or if this is node itself (most likely) and how to mitigate it. Any advice would be grateful.

```console
$ bazel build //...
INFO: Analyzed 1243 targets (0 packages loaded, 0 targets configured).
INFO: Found 1243 targets...
ERROR: /home/fredrik/code/monolith/modules/user/BUILD.bazel:4:12: Compiling TypeScript project //modules/user:user [tsc -p tsconfig.bazel.json] failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log snippet, file at /home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/bazel-workers/worker-14-TsProject.log ---8<---8<---
[... truncated ...]
9.3 (4125.2) -> 4034.8 (4126.7) MB, 86.5 / 0.0 ms  (average mu = 0.626, current mu = 0.669) allocation failure 
[21327:0x5fc7fc0]  2089077 ms: Scavenge 4041.0 (4126.7) -> 4037.0 (4128.7) MB, 69.3 / 0.1 ms  (average mu = 0.626, current mu = 0.669) allocation failure 
[21327:0x5fc7fc0]  2093077 ms: Scavenge 4043.4 (4129.5) -> 4039.4 (4147.0) MB, 3729.2 / 0.0 ms  (average mu = 0.626, current mu = 0.669) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09c10 node::Abort() [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 2: 0xa1c193 node::FatalError(char const*, char const*) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 3: 0xcf8dbe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 4: 0xcf9137 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 5: 0xeb09d5  [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 6: 0xec069d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 7: 0xec339e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 8: 0xe848da v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 9: 0x11fd626 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
10: 0x15f2099  [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh: line 440: 21327 Aborted                 (core dumped) "$JS_BINARY__NODE_WRAPPER" ${JS_BINARY__NODE_OPTIONS[@]+"${JS_BINARY__NODE_OPTIONS[@]}"} -- "$entry_point" ${ARGS[@]+"${ARGS[@]}"} 0<&0
---8<---8<--- End of log snippet, 104 chars omitted ---8<---8<---
ERROR: /home/fredrik/code/monolith/services/backend/BUILD.bazel:148:13 ImageLayer services/backend/docker-layer.tar failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log snippet, file at /home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/bazel-workers/worker-14-TsProject.log ---8<---8<---
[... truncated ...]
9.3 (4125.2) -> 4034.8 (4126.7) MB, 86.5 / 0.0 ms  (average mu = 0.626, current mu = 0.669) allocation failure 
[21327:0x5fc7fc0]  2089077 ms: Scavenge 4041.0 (4126.7) -> 4037.0 (4128.7) MB, 69.3 / 0.1 ms  (average mu = 0.626, current mu = 0.669) allocation failure 
[21327:0x5fc7fc0]  2093077 ms: Scavenge 4043.4 (4129.5) -> 4039.4 (4147.0) MB, 3729.2 / 0.0 ms  (average mu = 0.626, current mu = 0.669) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09c10 node::Abort() [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 2: 0xa1c193 node::FatalError(char const*, char const*) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 3: 0xcf8dbe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 4: 0xcf9137 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 5: 0xeb09d5  [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 6: 0xec069d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 7: 0xec339e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 8: 0xe848da v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
 9: 0x11fd626 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
10: 0x15f2099  [/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh.runfiles/monolith/../nodejs_linux_amd64/bin/nodejs/bin/node]
/home/fredrik/.cache/bazel/_bazel_fredrik/b93f0bbfc3437d73f39541651170604b/execroot/monolith/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/npm_typescript/tsc_worker.sh: line 440: 21327 Aborted                 (core dumped) "$JS_BINARY__NODE_WRAPPER" ${JS_BINARY__NODE_OPTIONS[@]+"${JS_BINARY__NODE_OPTIONS[@]}"} -- "$entry_point" ${ARGS[@]+"${ARGS[@]}"} 0<&0
---8<---8<--- End of log snippet, 104 chars omitted ---8<---8<---
INFO: Elapsed time: 516.078s, Critical Path: 220.24s
INFO: 1326 processes: 373 internal, 134 linux-sandbox, 703 local, 116 worker.
FAILED: Build did NOT complete successfully
```

Running with NodeJS version: 16.15.0

Not sure what info you want/need, I'll gladly provide what I can. :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by thesayyn**
fixes #175 and #141

### CODE REVIEW

File: ts/private/ts_project_worker.js [hunk 1]
```diff
@@ -540,23 +538,53 @@ function createProgram(args, initialInputs) {
...
         host.debuglog(`Created a new worker for ${key}`);
-        workers.set(key, {
+        worker = {
             program,
             host,
             checkAndApplyArgs
-        });
+        }
+    } else {
+        workers.delete(key)
```
Comment (jbedard) [inline ts/private/ts_project_worker.js:584]: When would it be in the map but falsy?

File: ts/private/ts_project_worker.js [hunk 2]
```diff
@@ -540,23 +538,53 @@ function createProgram(args, initialInputs) {
...
+
+/** @type {Map<string, ReturnType<createProgram> & {previousInputs?: import("@bazel/worker").Inputs}>} */
+const workers = new Map();
+
+function sweepLeastRecentlyUsedWorkers() {
+    for (const [k, w] of workers) {
+        w.program.close();
+        workers.delete(k);
+        // stop killing workers as soon as the worker is out the oom zone 
+        if (!isNearOomZone()) {
```
Comment (jbedard) [inline ts/private/ts_project_worker.js:558]: How about putting this at the start of the loop? Then we don't have to put it everywhere we invoke `sweepLeastRecentlyUsedWorkers`...

File: ts/private/ts_project_worker.js [hunk 3]
```diff
@@ -540,23 +538,53 @@ function createProgram(args, initialInputs) {
...
             program,
             host,
             checkAndApplyArgs
-        });
+        }
+    } else {
+        workers.delete(key)
     }
-    return workers.get(key);
+    workers.set(key, worker)
```
[the remark this answers is not in the document]
Comment (thesayyn) [reply ts/private/ts_project_worker.js:586]: nope. we want to move the worker in the map to the end by removing and setting it again so that we sweep the ones that haven't been used most recently.

[the remark this answers is not in the document]
Comment (thesayyn) [reply ts/private/ts_project_worker.js:586]: take this as an example; 
```js
const map = new Map();

map.set("1", "");
map.set("2", "");
map.set("3", "");

map.delete("1");
map.set("1", "");

console.log([...map.keys()]) // ["2", "3", "1"]
```

File: ts/private/ts_project_worker.js (hunk 1 above)
Comment (jbedard) [reply ts/private/ts_project_worker.js:584]: Oh... this is to ensure it gets put at the end again?

File: ts/private/ts_project_worker.js (hunk 2 above)
Comment (thesayyn) [reply ts/private/ts_project_worker.js:558]: yeah, that makes sense but way too smart thing to understand when we look at it later on. I am not sure.

File: ts/private/ts_project_worker.js (hunk 1 above)
Comment (thesayyn) [reply ts/private/ts_project_worker.js:584]: yeap.

File: ts/private/ts_project_worker.js (hunk 2 above)
Comment (thesayyn) [reply ts/private/ts_project_worker.js:558]: my thought process was `sweep workers if it is near the oom zone` and `kill workers until it gets out of the oom zone`

File: ts/private/ts_project_worker.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (jbedard) [reply ts/private/ts_project_worker.js:586]: I see 👍 

Lets just add a comment somewhere saying why we are deleting it and adding it again. Otherwise I'll look at this in a year and want to change it 😅

[the remark this answers is not in the document]
Comment (thesayyn) [reply ts/private/ts_project_worker.js:586]: right. I'll do that

File: ts/private/ts_project_worker.js (hunk 2 above)
Comment (jbedard) [reply ts/private/ts_project_worker.js:558]: But right now it essentially requires the `if` before invoking it..? Not a big deal though 🤷

**Review by jbedard — APPROVED** [review]

File: ts/private/ts_project_worker.js (hunk 2 above)
Comment (thesayyn) [reply ts/private/ts_project_worker.js:558]: exactly. I find it easier to read this way.

Comment (jbedard) [reply ts/private/ts_project_worker.js:558]: I was thinking just `avoid oom` and putting all the logic in one method. It's all internal though so doesn't really matter. Your choice 👍
