### PR TITLE
fix: support --experimental_allow_unresolved_symlinks flag

### LINKED ISSUE #166: Worker does not find 3rd party deps with Bazel 6 --experimental_allow_unresolved_symlinks
In https://github.com/aspect-build/bazel-examples:

```shell
$ export USE_BAZEL_VERSION=last_green    
$ cd next.js
$ bazel run start --experimental_allow_unresolved_symlinks

INFO: Analyzed target //:start (0 packages loaded, 1550 targets configured).
INFO: Found 1 target...
ERROR: /Users/matt/Documents/GitHub/bazel-examples/next.js/pages/api/BUILD.bazel:5:11: Compiling TypeScript project @//pages/api:api_typings [tsc -p tsconfig.json] failed: (Exit 1): tsc_worker.sh failed: error executing command (from target //pages/api:api_typings) bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/npm_typescript/tsc_worker.sh @bazel-out/darwin-fastbuild/bin/pages/api/hello.d.ts-0.params

pages/api/hello.ts(2,54): error TS2307: Cannot find module 'next' or its corresponding type declarations.

### PR DESCRIPTION
**Pull request by thesayyn**
fixes #166

### CODE REVIEW

File: ts/private/ts_project_worker.js [hunk 1]
```diff
@@ -101,10 +101,22 @@ function createFilesystemTree(root, inputs) {
...
             notifyWatchers(dirs, parts.base, TYPE.SYMLINK, EVENT_TYPE.ADDED);
         } else if (parts.base) {
-            node[parts.base] = {
-                [Type]: TYPE.FILE
+            const new_node = {
+                [Type]: TYPE.FILE,
             }
-            notifyWatchers(dirs, parts.base, TYPE.FILE, EVENT_TYPE.ADDED);
+            try {
+                const realpath = fs.readlinkSync(path.join(root, p));
```
Comment (gregmagolan) [inline ts/private/ts_project_worker.js:108]: `const stat = fs.lstatSync` will be faster here and you can check `stat.is_symlink()`

**Review by gregmagolan — APPROVED** [review]
🌮

File: e2e/worker/test.sh [hunk 2]
```diff
@@ -22,6 +22,9 @@ add_trap() {
     trap "(set +e; $traps)" EXIT
 }
 
+# fresh start since test.sh is run in sequential steps
+bazel clean
```
Comment (gregmagolan) [inline e2e/worker/test.sh:26]: @thesayyn If I don't bazel clean then the 2nd run of ./test.sh fails with 5.3.2 on test case 11. Might be worth trying to see if there is a potential bug there.
