### PR TITLE
fix: take project rescaling into consideration

### LINKED ISSUE #233: [Bug]: frequent OOMs on our CI instance
### What happened?

CI is flaky for this project, right now main is red:
https://github.com/aspect-build/rules_ts/actions/runs/3402670840/jobs/5658665739

### Version

HEAD

### How to reproduce

_No response_

### Any other information?

_No response_

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

### PR DESCRIPTION
**Pull request by thesayyn**
fixes #233

### CODE REVIEW

File: ts/private/ts_project_worker.js [hunk 1]
```diff
@@ -744,4 +744,4 @@ if (require.main === module && worker.runAsWorker(process.argv)) {
     }
 }
 
-module.exports = {createFilesystemTree: createFilesystemTree, emit: emit};
+module.exports.__do_not_use_test_only__ = {createFilesystemTree: createFilesystemTree, emit: emit, workers: workers};
```
Comment (jbedard) [inline ts/private/ts_project_worker.js:747]: Does anything other then tests import this file? Is this necessary?

**Review by jbedard — APPROVED** [review]

File: ts/private/ts_project_worker.js (hunk 1 above)
Comment (thesayyn) [reply ts/private/ts_project_worker.js:747]: this is not part of the public API. so no one should depend on it except test in this repo.

Comment (jbedard) [reply ts/private/ts_project_worker.js:747]: Shouldn't no one even depend on the file though? I don't really see the value in adding a funny name 🤷
